 version: '3.7'
 services:
   registration-bot-postgres:
     container_name: registration-bot-container
     image: postgres:10.7
     ports:
       - 5434:5432
     environment:
       - POSTGRES_PASSWORD=12345678
       - POSTGRES_USER=postgres
       - POSTGRES_DB=reg_bot
     restart: always